volumes:
  db:
  static:

services:
  db:
    image: postgres:17.2
    env_file:
      - ../.env
    volumes:
      - db:/var/lib/postgresql/data
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    command: gunicorn --bind 0.0.0.0:8000 dog_api.wsgi
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - static:/app/static/
    depends_on:
      - db

  nginx:
    image: nginx:1.26.2
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
    depends_on:
      - backend